#!/bin/sh -
# BEGIN LICENSE BLOCK
# Version: CMPL 1.1
#
# The contents of this file are subject to the Cisco-style Mozilla Public
# License Version 1.1 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License
# at www.eclipse-clp.org/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License. 
# 
# The Original Code is  The ECLiPSe Constraint Logic Programming System. 
# The Initial Developer of the Original Code is  Cisco Systems, Inc. 
# Portions created by the Initial Developer are
# Copyright (C) 1990,2006 Cisco Systems, Inc.  All Rights Reserved.
# 
# Contributor(s): ___________________________________. 
# 
# END LICENSE BLOCK
#
# $Id: fixmanual,v 1.1 2006/09/23 01:54:31 snovello Exp $
#

# Fix the manual file

ex $1 <<\EOF
%s/_/\\_/g
w
q
EOF
ex $1 <<\EOF
%s/</$<$/g
w
q
EOF
ex $1 <<\EOF
%s/>/$>$/g
w
q
EOF
ex $1 <<\EOF
%s/\\==/$\\backslash$==/g
w
q
EOF
ex $1 <<\EOF
%s/\\=/$\\backslash$=/g
w
q
EOF
ex $1 <<\EOF
%s/=/$=$/g
w
q
EOF
ex $1 <<\EOF
%s/\~/\\verb+\~+/g
w
q
EOF




