/*
 * Copyright (c) 2014 ETH Zurich.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Universitaetsstrasse 64, CH-8092 Zurich. Attn: Systems Group.
 */

#ifndef __BOMP_TASK_H
#define __BOMP_TASK_H

/*
 * A specific instance of executable code and its data environment, generated when
 * a thread encounters a task construct or a parallel construct.
 *
 * implicit task:  A task generated by an implicit parallel region or generated
 * when a parallel construct is encountered during execution.
 */
struct bomp_task
{

};

#endif	/* __BOMP_TEAM_H */
