/**
 * \file
 * \brief C++ startup code. Contains .ctor section footer and ABI support.
 */

/*
 * Copyright (c) 2007, 2008, 2009, 2010, ETH Zurich.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Haldeneggsteig 4, CH-8092 Zurich. Attn: Systems Group.
 */

#include <stdio.h>
#include <sys/_types.h>

typedef void (*CDtor)(void);

static CDtor ctors[1]
__attribute__ ((used, section(".ctors"), aligned(sizeof(CDtor))))
    = { (CDtor)(0) };

int __cxa_atexit(void (*func)(void *), void *arg, void *d);

/* Register a function to be called by exit or when a shared library
   is unloaded.  This function is only called from code generated by
   the C++ compiler.  */
int __cxa_atexit(void (*func)(void *), void *arg, void *d)
{
    printf("__cxa_atexit ignored\n");
    // XXX: We do nothing yet
    return 0;
}
