#! /bin/sh
# BEGIN LICENSE BLOCK
# Version: CMPL 1.1
#
# The contents of this file are subject to the Cisco-style Mozilla Public
# License Version 1.1 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License
# at www.eclipse-clp.org/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License. 
# 
# The Original Code is  The ECLiPSe Constraint Logic Programming System. 
# The Initial Developer of the Original Code is  Cisco Systems, Inc. 
# Portions created by the Initial Developer are
# Copyright (C) 2006 Cisco Systems, Inc.  All Rights Reserved.
# 
# Contributor(s): 
# 
# END LICENSE BLOCK

if test -z "$ECLIPSEARCH"; then
        echo Please set environment variable ECLIPSEARCH and try again
        exit -1
fi

make_directory ()       # <perm> <name>
{
    # explicit checking for symlink is for linux, where test is broken
    if test ! -d $2 && (test "$ECLIPSEARCH" != "i386_linux" || test ! -h $2); then
        mkdir $2
        chmod $1 $2
    fi
}

install_file ()		# <perm> <file> <dir>
{
    echo installing $3/$2
    cp $2 $3/$2
    chmod $1 $3/$2
}

make_directory 2755 ../doc
make_directory 2755 ../doc/examples

DEST=../doc/examples

install_file 755 EclipseClass.cls $DEST
install_file 755 EclipseStream.cls $DEST
install_file 755 EclipseStreams.cls $DEST
install_file 755 EclipseThread.vbp $DEST
