#! /bin/sh
#! /bin/sh

# BEGIN LICENSE BLOCK
# Version: CMPL 1.1
#
# The contents of this file are subject to the Cisco-style Mozilla Public
# License Version 1.1 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License
# at www.eclipse-clp.org/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License. 
# 
# The Original Code is  The ECLiPSe Constraint Logic Programming System. 
# The Initial Developer of the Original Code is  Cisco Systems, Inc. 
# Portions created by the Initial Developer are
# Copyright (C) 2006 Cisco Systems, Inc.  All Rights Reserved.
# 
# Contributor(s): 
# 
# END LICENSE BLOCK

make_directory ()       # <perm> <name>
{
    # explicit checking for symlink is for linux, where test is broken
    if test ! -d $2 && (test "$ECLIPSEARCH" != "i386_linux" || test ! -h $2); then
        mkdir $2
        chmod $1 $2
    fi
}

install_file ()		# <perm> <file> <dir>
{
    cp $2 $3/$2
    chmod $1 $3/$2
}

make_directory 2755 ../../doc
make_directory 2755 ../../doc/bips
make_directory 2755 ../../doc/bips/kernel
cp -pr kernel/*.eci ../../doc/bips/kernel
chmod 644 ../../doc/bips/kernel/*.eci

#eclipse -e 'use_module(gendoc),man_chapter'

#TEXINPUTS=../texinputs:$TEXINPUTS
#BIBINPUTS=../texinputs
#export TEXINPUTS BIBINPUTS

#make install

